server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: invoice-service-group
      auto-offset-reset: earliest
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/vms_db_01}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

invoice:
  topic: invoice-submitted
